sudo: required
language: node_js
services: docker
node_js:
- "12"

before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
- npm test
- npm run test-ui
