version: '2'

services:
  web:
    build: .
    ports:
    - 8000:8000
    links:
    - database
    environment:
    - USER
  database:
    image: postgres
    volumes:
    - ./docs/schema.sql:/docker-entrypoint-initdb.d/init.sql
