# WIP API description

openapi: '3.0.2'
info:
  title: 'oss-attribution-builder API'
  version: '1.0.0'
servers:
  - url: 'http://localhost:8000/api/'
security:
  - nullauth: []

components:
  securitySchemes:
    nullauth:
      type: http
      scheme: basic

  parameters:
    projectId:
      in: path
      name: projectId
      required: true
      schema:
        type: string
    documentId:
      in: path
      name: documentId
      required: true
      schema:
        type: number

  schemas:
    project:
      type: object
      properties:
        projectId:
          type: string
        title:
          type: string
        version:
          type: string
        description:
          type: string
        createdOn:
          type: string
        plannedRelease:
          type: string
        contacts:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        acl:
          type: object
          additionalProperties:
            type: string
        packagesUsed:
          type: array
          items:
            type: object
        refs:
          type: object
        metadata:
          type: object
        access:
          type: object
          properties:
            level:
              type: string
            canEdit:
              type: boolean

    package:
      type: object
      properties:
        packageId:
          type: string
        name:
          type: string
        version:
          type: string
        website:
          type: string
        copyright:
          type: string
        license:
          type: string
        licenseText:
          type: string

    packageWithUsage:
      type: object

    attributionDocument:
      type: object
      properties:
        id:
          type: number
        projectId:
          type: string
        projectVersion:
          type: string
        createdOn:
          type: string
        createdBy:
          type: string
        content:
          type: string

paths:
  /v1/info:
    get:
      summary: get session info
      responses:
        200:
          description: current user's session info
          content:
            application/json:
              schema:
                type: object
                properties:
                  displayName:
                    type: string
                  groups:
                    type: array
                    items:
                      type: string
                  permissions:
                    type: object
                    properties:
                      admin:
                        type: boolean

  /v1/projects:
    get:
      summary: get all accessible projects
      responses:
        200:
          description: list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    projectId:
                      type: string
                    title:
                      type: string
                    version:
                      type: string
                    createdOn:
                      type: string

  /v1/projects/{projectId}:
    get:
      summary: get project by id
      parameters:
        - $ref: '#/components/parameters/projectId'
      responses:
        200:
          description: project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/project'

    patch:
      summary: edit project details
      description: Selectively edit primary details of a project. Any fields not included will not be modified.
      parameters:
        - $ref: '#/components/parameters/projectId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: []
              properties:
                title:
                  type: string
                  required: false
                version:
                  type: string
                  required: false
                description:
                  type: string
                  required: false
                plannedRelease:
                  type: string
                  required: false
                contacts:
                  type: object
                  required: false
                acl:
                  type: object
                  required: false
                metadata:
                  type: object
                  required: false
            example:
              title: 'My new project title'
      responses:
        200:
          description: successfully edited project

  /v1/projects/{projectId}/attach:
    post:
      summary: attach a package to the project
      parameters:
        - $ref: '#/components/parameters/projectId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                packageId:
                  type: string
                name:
                  type: string
                version:
                  type: string
                website:
                  type: string
                copyright:
                  type: string
                license:
                  type: string
                licenseText:
                  type: string
                usage:
                  type: object
            examples:
              add-single-package:
                summary: add a package by ID only
                value:
                  packageId: 12345

      responses:
        200:
          description: package was attached

  /v1/projects/{projectId}/build:
    get:
      summary: preview attribution document and annotations
      parameters:
        - $ref: '#/components/parameters/projectId'

      responses:
        200:
          description: attribution document preview and annotations
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                  annotations:
                    type: array
                    items:
                      type: object # TODO
                      properties:
                        lines:
                          type: array
                          minItems: 2
                          maxItems: 2
                        type:
                          type: string
                  summary:
                    type: object

    post:
      summary: generate and store attribution document
      parameters:
        - $ref: '#/components/parameters/projectId'

      responses:
        200:
          description: attribution document preview and annotations
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                  documentId:
                    type: number

  /v1/projects/{projectId}/docs:
    get:
      summary: list project's stored attribution documents
      parameters:
        - $ref: '#/components/parameters/projectId'

      responses:
        200:
          description: a list of all attribution documents attached to this project
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        projectVersion:
                          type: string
                        createdOn:
                          type: string
                        createdBy:
                          type: string

  /v1/projects/{projectId}/docs/{documentId}:
    get:
      summary: fetch a rendered attribution document
      description: Fetches an attribution document attached to a project. Includes information about when the document was created; a plain-text-only version can be fetched by appending `.text` to the end of the URL.
      parameters:
        - $ref: '#/components/parameters/projectId'
        - $ref: '#/components/parameters/documentId'

      responses:
        200:
          description: a rendered attribution document with details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/attributionDocument'

  /v1/packages/:
    post:
      summary: search packages

      responses:
        200:
          description: search results
